/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Devang' at '6/4/19 5:36 PM' with Gradle 3.0
 *
 * @author Devang, @date 6/4/19 5:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
